version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.14'
  commands:
    - pip install uv --disable-pip-version-check
    - uv run --group docs --locked sphinx-build -E docs $READTHEDOCS_OUTPUT/html

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
