name: Checks

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  check-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Cache dependencies
      id: python-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements-dev.txt') }}
    - name: Install dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt -e .
    - name: Check style
      run: |
        task lint_flake8
    - name: Check typing
      run: |
        task lint_mypy
    - name: Check imports
      run: |
        task lint_isort
    - name: Check formatting
      run: |
        task lint_black
  run-tests:
    name: Test on Python ${{ matrix.python-version }}
    needs: check-quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      id: python-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements-dev.txt') }}
    - name: Install dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt -e .
    - name: Run tests
      run: |
        task test_all
  check-coverage:
    name: Check code coverage
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Cache dependencies
      id: python-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements-dev.txt') }}
    - name: Install dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt -e .
    - name: Generate report
      run: |
        task test_cov
